### ISSUE TITLE
batch.propertiesで指定できるパラメータで、機能説明書説明書にないパラメータ

### ISSUE THREAD

**Issue by kudoueiji** [terasoluna-batch/terasoluna-doc#1]
batch.propertiesで指定できるパラメータで、
機能説明書に記載のないものとして以下４つがあるようです。

batchTaskExecutor.availableThreadThresholdCount=100
batchTaskExecutor.availableThreadThresholdWait=30
batchTaskExecutor.executeRetryInterval=100
batchTaskExecutor.executeRetryCountMax=1

非推奨のパラメータでなければ、マニュアルに記載した方が良いのではないでしょうか。

**Comment by kuramotoki** [comment]
コメントありがとうございます。
当該パラメータについては、ver3.6.0にて実装上も使わないように変更したため、
機能説明書には記述不要となりました。
本Issueはクローズします。
