### ISSUE TITLE
メッセージ管理機能の概念図 

### ISSUE THREAD

**Issue by kudoueiji** [terasoluna-batch/terasoluna-doc#2]
TERASOLUNA Batch Framework for Java 機能説明書(引用資料).pdf
の「CE-01 メッセージ管理機能」で使用されている概念図が
APサーバ上で画面に国際化対応したメッセージを表示するものになっています。

バッチで使用する前提でのドキュメントかと思いますので、
概念図をバッチ前提のものに変更した方が良いのではないでしょうか。

**Comment by kuramotoki** [comment]
コメントありがとうございます。
ver3.6.0にて概念図を修正しましたのでご確認ください。
また、引用資料はBL-09 メッセージ管理機能に統合しました。
本Issueはクローズします。
