### ISSUE TITLE
メッセージ管理関連の機能の使い分けについて、まとめた情報が欲しい 

### ISSUE THREAD

**Issue by kudoueiji** [terasoluna-batch/terasoluna-doc#3]
「TERASOLUNA Batch Framework for Java 機能説明書(引用資料).pdf」
「TERASOLUNA Batch Framework for Java 機能説明書.pdf」
のメッセージ管理機能や入力チェック機能の説明の中で
・MessageSource
・MessageUtil
・MessageAccessorImpl
を利用している箇所があります。
それぞれの特徴（できる、できない）や利用方針をまとめた情報を記載した方が良いように思いました。
※特にMessageUtilは読み込んでいる設定が、他の２つとは異なるため、その点を、マニュアルに記載しておいた方が良いかと思います。

**Comment by kuramotoki** [comment]
コメントありがとうございます。
ver3.6.0にて、メッセージ管理関連のAPIを`MessageAccessor(Impl)`に一本化し、`MessageUtil`を非推奨としました。
この対応で以前のVerと同等の処理を実現できると考えておりますが、問題等ございましたら別Issueにてお教えいただければと存じます。
本Issueはクローズします。
