### ISSUE TITLE
非同期ジョブ実行で実行するジョブを限定する方法

### ISSUE THREAD

**Issue by kudoueiji** [terasoluna-batch/terasoluna-doc#5]
非同期ジョブ実行機能で、AsyncBatchExecutorの引数に業務ジョブコードを指定することで、
指定した業務ジョブコードのバッチのみ起動できるようですが、機能説明書には記載がありません。
記載した方が良いのではないでしょうか。

**Comment by kuramotoki** [comment]
コメントありがとうございます。
ver3.6.0の修正にて、`指定した業務ジョブコードのバッチのみ起動`する処理はデフォルト実装からはずしました。そのうえで、同等の処理は拡張ポイントを利用することで実現できるようにし、その旨を`BL-02 非同期型ジョブ実行機能 - リファレンス - 拡張ポイント - JobControlFinderの拡張`に記載しました。

本Issueはクローズします。
