### ISSUE TITLE
チュートリアル（コントロールブレイク）の図の誤り

### ISSUE THREAD

**Issue by kudoueiji** [terasoluna-batch/terasoluna-doc#6]
「TERASOLUNA Batch Framework for Java チュートリアルマニュアル.pdf」の
「2.5 コントロールブレイク機能を利用した、 入力が フ ァイル、出力がフである場合の ァイル、出力がフである場合の ジョブ (同期 型ジョブ実行 )」
最初に、コントロールブレイクの機能を利用したジョブ(SMP004)の処理を説明した図(P54)があります。
ジョブ(SMP004)の実装では、図中の「２」に示す一行一行を読む度に、出力用入出金ファイルに入出金データを出力するような処理は実装されていません。ですので、図中の「２」は不要かと思います。

**Comment by kuramotoki** [comment]
コメントありがとうございます。
ver3.6.0で修正しましたのでご確認ください。
本Issueはクローズします。
