### ISSUE TITLE
記述誤：固定長ファイル入出力時のbytes指定可否

### ISSUE THREAD

**Issue by ikeyat** [terasoluna-batch/terasoluna-doc#7]
# Description

BC-01%20ファイルアクセス機能.pdf
の、P.7/26の表の固定長のbytesが×となっているが、◎もしくは○の記述誤りでないか？
P.18/26には、固定長でbytesを使用したコード例が紹介されているので設定不可（×）ということはないはず。

https://github.com/terasoluna-batch/terasoluna-doc/blob/master/function/%E5%BC%95%E7%94%A8%E8%B3%87%E6%96%99/BC-01%20%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E6%A9%9F%E8%83%BD.pdf

**Comment by kuramotoki** [comment]
コメントありがとうございます。
ver3.6.0にて表の記述内容を見直し修正しました。
本Issueはクローズします。
